# This file was generated by GoReleaser. DO NOT EDIT.
cask "kage" do
  version "0.3.12"

  on_macos do
    on_intel do
      sha256 "06f02ae1bf8cd2f517d9b596f99dfd1bc370abb017dadd9f05699a1fd21cec7d"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "df02cfebb29328acc194001ae23b331828b13039b09e417a1aa50e6897416364"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96560dc38f5af3dcb1744466abb0d60aaa55f1e98fd91008bbcfad21414d5b7b"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fce501df4822b27a20802c7ed0b04de3518502e94fed22c34a522fb090048f1c"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kage"
  desc "Clone any website for offline viewing, with the JavaScript stripped out"
  homepage "https://github.com/tamnd/kage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kage"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kage"], must_succeed: false
    end
  end

  # No zap stanza required

end
